name: Bump version, push tag, and publish to npm

on:
  push:
    branches:
      - master  # 如为 main，请改为 main

jobs:
  bump-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: 'https://registry.npmjs.org/'

      # 自动递增 patch 版本号
      - name: Bump patch version
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          npm version patch --no-git-tag-version

      # Commit 递增的版本号（忽略 package-lock.json 不存在的报错）
      - name: Commit version bump
        run: |
          git add package.json || true
          [ -f package-lock.json ] && git add package-lock.json || true
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git push

      # 打 tag 并推送
      - name: Git tag
        run: |
          TAG="v$(node -p "require('./package.json').version")"
          git tag $TAG
          git push origin $TAG

      # 发布到 npm
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}